NAME           = opt-python-27
VERSION        = 2.7.8
RELEASE        = 1
PKGROOT        = /opt/python

SRC_SUBDIR     = python-2

SOURCE_NAME    = Python
SOURCE_SUFFIX  = tgz
SOURCE_VERSION = $(VERSION)
SOURCE_PKG     = $(SOURCE_NAME)-$(SOURCE_VERSION).$(SOURCE_SUFFIX)
SOURCE_DIR     = $(SOURCE_PKG:%.$(SOURCE_SUFFIX)=%)

NOSE_NAME      = nose
NOSE_SUFFIX    = tar.gz
NOSE_VERSION   = 1.3.4
NOSE_PKG       = $(NOSE_NAME)-$(NOSE_VERSION).$(NOSE_SUFFIX)
NOSE_DIR       = $(NOSE_PKG:%.$(NOSE_SUFFIX)=%)

NUMPY_NAME     = numpy
NUMPY_SUFFIX   = tar.gz
NUMPY_VERSION  = 1.8.0
NUMPY_PKG      = $(NUMPY_NAME)-$(NUMPY_VERSION).$(NUMPY_SUFFIX)
NUMPY_DIR      = $(NUMPY_PKG:%.$(NUMPY_SUFFIX)=%)

SETUPTOOLS_NAME     = setuptools
SETUPTOOLS_SUFFIX   = tar.gz
SETUPTOOLS_VERSION  = 7.0
SETUPTOOLS_PKG      = $(SETUPTOOLS_NAME)-$(SETUPTOOLS_VERSION).$(SETUPTOOLS_SUFFIX)
SETUPTOOLS_DIR      = $(SETUPTOOLS_PKG:%.$(SETUPTOOLS_SUFFIX)=%)

TGZ_PKGS       = $(SOURCE_PKG)
TAR_GZ_PKGS    = $(NOSE_PKG) $(NUMPY_PKG) $(SETUPTOOLS_PKG)

RPM.EXTRAS     = AutoReq:No
