NAME		= opt-python-27
PKGROOT		= /opt/python
ARCHIVENAME    	= Python
VERSION 	= 2.7.5
RELEASE 	= 3
TARBALL_POSTFIX	= tgz

SRC_SUBDIR	= python-2

PYTHON2_NAME	= $(ARCHIVENAME)
PYTHON2_VERSION	= $(VERSION)
NUMPY_NAME      = numpy
NUMPY_VERSION   = 1.8.0
NUMPY_SUFFIX     = tar.gz
NUMPY_PKG        = $(NUMPY_NAME)-$(NUMPY_VERSION).$(NUMPY_SUFFIX)
NUMPY_DIR        = $(NUMPY_PKG:%.$(NUMPY_SUFFIX)=%)


# List of *.tgz packages that are part of THIS package
TGZ_PKGS = $(PYTHON2_NAME)-$(PYTHON2_VERSION).$(TARBALL_POSTFIX)
TAR_GZ_PKGS = $(NUMPY_PKG)
