NAME           = sdsc-python-3
VERSION        = 3.4.2
MAJOR.MINOR    = 3.4
RELEASE        = 1
PKGROOT        = /opt/python

SRC_SUBDIR     = python-3

SOURCE_NAME    = Python
SOURCE_SUFFIX  = tgz
SOURCE_VERSION = $(VERSION)
SOURCE_PKG     = $(SOURCE_NAME)-$(SOURCE_VERSION).$(SOURCE_SUFFIX)
SOURCE_DIR     = $(SOURCE_PKG:%.$(SOURCE_SUFFIX)=%)

NUMPY_NAME     = numpy
NUMPY_SUFFIX   = tar.gz
NUMPY_VERSION  = 1.8.0
NUMPY_PKG      = $(NUMPY_NAME)-$(NUMPY_VERSION).$(NUMPY_SUFFIX)
NUMPY_DIR      = $(NUMPY_PKG:%.$(NUMPY_SUFFIX)=%)

TGZ_PKGS       = $(SOURCE_PKG)
TAR_GZ_PKGS    = $(NUMPY_PKG)

RPM.EXTRAS     = AutoReq:No
